# Generated by Django 5.1.15 on 2026-09-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='type_marche',
            field=models.CharField(choices=[('appel_offres', "Appel d'offres"), ('avis_attribution', "Avis d'attribution"), ('plan_passation', 'Plan de passation'), ('manifestation_interet', "Manifestation d'intérêt")], default='appel_offres', max_length=24, verbose_name='Type de publication'),
        ),
    ]
