# Generated by Django 5.1.15 on 2026-09-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitebrandsettings_sponsor_image'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Afficher la bannière')),
                ('link', models.URLField(blank=True, help_text='Lien optionnel vers la page partenaire ou la campagne.', verbose_name='Lien de la bannière')),
                ('image', models.ForeignKey(blank=True, help_text="Si vide, l'image statique huj.png est utilisée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de la bannière')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Bannière partenaire',
            },
        ),
        migrations.DeleteModel(
            name='SiteBrandSettings',
        ),
    ]
