# Generated by Django 5.1.15 on 2026-09-21 21:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('callout', 9), ('cta', 12), ('table', 18), ('org_chart', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Titre 2'), ('h3', 'Titre 3')], 'label': 'Niveau'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.core.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Description de l'image pour l'accessibilité (obligatoire).", 'label': 'Texte alternatif', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('alt', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Contenu'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé du bouton'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Lien'}), 12: ('wagtail.blocks.StructBlock', [[('label', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'En-tête'}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'En-têtes'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Cellule'}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Ligne'}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Lignes'}), 18: ('wagtail.blocks.StructBlock', [[('headers', 14), ('rows', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex. : Directions sectorielles.', 'label': 'Titre du groupe'}), 20: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Cartes plus grandes, pour la direction générale.', 'label': 'Mettre en avant', 'required': False}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Nom'}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Fonction ou direction'}), 24: ('wagtail.blocks.StructBlock', [[('image', 21), ('name', 22), ('role', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Personnes'}), 26: ('wagtail.blocks.StructBlock', [[('title', 19), ('featured', 20), ('members', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'Groupes'}), 28: ('wagtail.blocks.StructBlock', [[('groups', 27)]], {})}, verbose_name='Contenu'),
        ),
    ]
