# Generated by Django 5.1.15 on 2026-09-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "referentiel",
                    models.CharField(
                        choices=[
                            ("iso9001", "ISO 9001 — Qualité"),
                            ("iso14001", "ISO 14001 — Environnement"),
                            ("iso45001", "ISO 45001 — Santé & sécurité au travail"),
                        ],
                        max_length=20,
                        verbose_name="Référentiel",
                    ),
                ),
                ("perimetre", models.CharField(max_length=255, verbose_name="Périmètre certifié")),
                (
                    "organisme",
                    models.CharField(max_length=120, verbose_name="Organisme certificateur"),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=80, verbose_name="N° de certificat"),
                ),
                ("date_emission", models.DateField(verbose_name="Date d'émission")),
                ("date_validite", models.DateField(verbose_name="Valide jusqu'au")),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Certificat (PDF)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["referentiel"],
            },
        ),
    ]
