# Generated by Django 5.1.15 on 2026-09-20 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualite', '0004_certification_visual'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageqse',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Photo affichée sur la carte de cette rubrique (accueil). Décorative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo de la rubrique'),
        ),
    ]
