# Generated by Django 5.1.15 on 2026-09-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebrandsettings',
            name='sponsor_image',
            field=models.ForeignKey(blank=True, help_text='Image optionnelle; sinon le bandeau PAD AGORA local est utilisé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image du bandeau partenaire'),
        ),
    ]
