# Generated by Django 5.1.15 on 2026-09-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sponsorbannersettings_delete_sitebrandsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorBannerSettings',
        ),
    ]
