# Generated by Django 5.1.15 on 2026-09-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_sponsor_banner_settings'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListHeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navires_eyebrow', models.CharField(blank=True, default='Trafic maritime', max_length=120, verbose_name='Sur-titre')),
                ('navires_title', models.CharField(blank=True, default='Mouvement des navires', max_length=140, verbose_name='Titre')),
                ('navires_intro', models.TextField(blank=True, default='Suivez les arrivées, les escales à quai et les départs du port de Dakar.', verbose_name="Texte d'introduction")),
                ('croisieres_eyebrow', models.CharField(blank=True, default='Infos pratiques', max_length=120, verbose_name='Sur-titre')),
                ('croisieres_title', models.CharField(blank=True, default='Escales de croisière', max_length=140, verbose_name='Titre')),
                ('croisieres_intro', models.TextField(blank=True, default='Le calendrier des paquebots attendus au Port Autonome de Dakar, avec leur poste à quai et leur consignataire.', verbose_name="Texte d'introduction")),
                ('marches_eyebrow', models.CharField(blank=True, default='Transparence et commande publique', max_length=120, verbose_name='Sur-titre')),
                ('marches_title', models.CharField(blank=True, default='Marchés publics', max_length=140, verbose_name='Titre')),
                ('marches_intro', models.TextField(blank=True, default="Consultez les appels d'offres, avis d'attribution et plans de passation du Port Autonome de Dakar.", verbose_name="Texte d'introduction")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Textes des pages de listes',
            },
        ),
    ]
