# Generated by Django 5.1.15 on 2026-09-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Non classé'), ('strategique', 'Stratégique'), ('institutionnel', 'Institutionnel'), ('international', 'International')], default='', max_length=16, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='module',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('marches:appel_offres', "Liste : appels d'offres"), ('marches:avis_attribution', "Liste : avis d'attribution"), ('marches:plan_passation', 'Liste : plan de passation'), ('marches:manifestation_interet', "Liste : manifestations d'intérêt"), ('articles:actualite', 'Liste : actualités'), ('articles:communique', 'Liste : communiqués de presse'), ('articles:photos', 'Liste : photothèque / vidéothèque'), ('partners:strategique', 'Partenaires stratégiques'), ('partners:institutionnel', 'Partenaires institutionnels'), ('partners:international', 'Partenaires internationaux'), ('key_figures', "Chiffres clés de l'accueil"), ('subpages', 'Cartes vers les sous-pages')], default='', help_text='Affiche automatiquement une liste sous le contenu de la page.', max_length=40, verbose_name='Module dynamique'),
        ),
    ]
