# Generated by Django 5.1.15 on 2026-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navires', '0002_escale_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Croisiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'escale")),
                ('navire', models.CharField(max_length=120, verbose_name='Navire')),
                ('poste', models.CharField(blank=True, max_length=40, verbose_name='Poste à quai')),
                ('consignataire', models.CharField(blank=True, max_length=140, verbose_name='Consignataire')),
            ],
            options={
                'verbose_name': 'Escale de croisière',
                'verbose_name_plural': 'Escales de croisière',
                'ordering': ['date', 'navire'],
                'constraints': [models.UniqueConstraint(fields=('date', 'navire'), name='croisiere_date_navire_unique')],
            },
        ),
    ]
