# Generated by Django 5.1.15 on 2026-09-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navire', models.CharField(max_length=120, verbose_name='Nom du navire')),
                ('type_navire', models.CharField(choices=[('conteneur', 'Conteneur'), ('cargo', 'Cargo'), ('vrac', 'Vrac'), ('passagers', 'Passagers'), ('croisiere', 'Cruise')], default='conteneur', max_length=20, verbose_name='Type de navire')),
                ('pavillon', models.CharField(max_length=80, verbose_name='Pavillon')),
                ('provenance', models.CharField(max_length=120, verbose_name='Provenance')),
                ('destination', models.CharField(max_length=120, verbose_name='Destination')),
                ('quai', models.CharField(blank=True, max_length=80, verbose_name='Quai')),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('statut', models.CharField(choices=[('attendu', 'Attendu'), ('a_quai', 'À quai'), ('parti', 'Parti')], default='attendu', max_length=20, verbose_name='Statut')),
                ('consignataire', models.CharField(blank=True, max_length=140, verbose_name='Consignataire')),
            ],
            options={
                'verbose_name': 'Escale',
                'verbose_name_plural': 'Escales',
                'ordering': ['date_arrivee', 'navire'],
            },
        ),
    ]
