# Generated by Django 5.1.15 on 2026-09-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='share_image',
            field=models.ForeignKey(blank=True, help_text='Image utilisée dans les aperçus de partage (Open Graph).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage'),
        ),
        migrations.AddField(
            model_name='serviceindexpage',
            name='share_image_alt',
            field=models.CharField(blank=True, help_text="Obligatoire lorsqu'une image de partage est sélectionnée.", max_length=255, verbose_name="Texte alternatif de l'image de partage"),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='share_image',
            field=models.ForeignKey(blank=True, help_text='Image utilisée dans les aperçus de partage (Open Graph).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='share_image_alt',
            field=models.CharField(blank=True, help_text="Obligatoire lorsqu'une image de partage est sélectionnée.", max_length=255, verbose_name="Texte alternatif de l'image de partage"),
        ),
    ]
