# Generated by Django 5.1.15 on 2026-09-19 13:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceindexpage_share_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('callout', 9), ('cta', 12), ('table', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Titre 2'), ('h3', 'Titre 3')], 'label': 'Niveau'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.core.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Description de l'image pour l'accessibilité (obligatoire).", 'label': 'Texte alternatif', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('alt', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Contenu'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé du bouton'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Lien'}), 12: ('wagtail.blocks.StructBlock', [[('label', 10), ('url', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'En-tête'}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'En-têtes'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Cellule'}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Ligne'}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Lignes'}), 18: ('wagtail.blocks.StructBlock', [[('headers', 14), ('rows', 17)]], {})}, verbose_name='Contenu'),
        ),
    ]
