# Generated by Django 5.1.15 on 2026-09-19 10:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('share_image_alt', models.CharField(blank=True, help_text="Obligatoire lorsqu'une image de partage est sélectionnée.", max_length=255, verbose_name="Texte alternatif de l'image de partage")),
                ('summary', models.CharField(max_length=255, verbose_name='Résumé')),
                ('category', models.CharField(choices=[('actualite', 'Actualité'), ('communique', 'Communiqué'), ('evenement', 'Événement'), ('photos', 'Photos et vidéos')], default='actualite', max_length=20, verbose_name='Catégorie')),
                ('publication_date', models.DateField(verbose_name='Date de publication')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('callout', 9), ('cta', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Titre 2'), ('h3', 'Titre 3')], 'label': 'Niveau'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('apps.core.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Description de l'image pour l'accessibilité (obligatoire).", 'label': 'Texte alternatif', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('alt', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Contenu'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé du bouton'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Lien'}), 12: ('wagtail.blocks.StructBlock', [[('label', 10), ('url', 11)]], {})}, verbose_name='Contenu')),
                ('cover_alt', models.CharField(blank=True, help_text="Obligatoire lorsqu'une image principale est sélectionnée.", max_length=255, verbose_name="Texte alternatif de l'image principale")),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_articles', to='wagtailimages.image', verbose_name='Image principale')),
                ('share_image', models.ForeignKey(blank=True, help_text='Image utilisée dans les aperçus de partage (Open Graph).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'verbose_name': 'Article média',
                'verbose_name_plural': 'Articles média',
                'ordering': ['-publication_date', '-first_published_at'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='MediaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('share_image_alt', models.CharField(blank=True, help_text="Obligatoire lorsqu'une image de partage est sélectionnée.", max_length=255, verbose_name="Texte alternatif de l'image de partage")),
                ('intro', models.CharField(blank=True, max_length=255, verbose_name='Introduction')),
                ('share_image', models.ForeignKey(blank=True, help_text='Image utilisée dans les aperçus de partage (Open Graph).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de partage')),
            ],
            options={
                'verbose_name': 'Index média',
                'verbose_name_plural': 'Index média',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
