# Generated by Django 5.1.15 on 2026-09-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='category',
            field=models.CharField(choices=[('actualite', 'Actualité'), ('communique', 'Communiqué'), ('note', 'Note aux usagers'), ('evenement', 'Événement'), ('photos', 'Photos et vidéos')], default='actualite', max_length=20, verbose_name='Catégorie'),
        ),
    ]
