# Generated by Django 5.1.15 on 2026-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('reference', models.CharField(max_length=80, unique=True, verbose_name='Référence')),
                ('type_marche', models.CharField(choices=[('appel_offres', "Appel d'offres"), ('avis_attribution', "Avis d'attribution"), ('plan_passation', 'Plan de passation')], default='appel_offres', max_length=24, verbose_name='Type de publication')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite de dépôt')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé'), ('attribue', 'Attribué')], default='ouvert', max_length=12, verbose_name='Statut')),
                ('documents', models.ManyToManyField(blank=True, related_name='marches_publics', to='wagtaildocs.document', verbose_name='Documents attachés')),
            ],
            options={
                'verbose_name': 'Marché public',
                'verbose_name_plural': 'Marchés publics',
                'ordering': ['-date_publication', 'reference'],
            },
        ),
    ]
