# Generated by Django 5.1.15 on 2026-09-19 20:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_homepage_body_alter_standardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Unique h1 de la page. Valeur par défaut si vide.', max_length=120, verbose_name='Titre principal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='key_figures',
            field=wagtail.fields.StreamField([('figure', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex. : 22,5 M', 'label': 'Valeur', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé', 'max_length': 80}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Source / année', 'max_length': 120, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1), ('source', 2)]], {})}, help_text="Bandeau de chiffres officiels (6 maximum). Masqué s'il est vide.", verbose_name='Chiffres clés'),
        ),
    ]
