# Generated by Django 5.1.15 on 2026-09-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière mise à jour'),
        ),
    ]
