# Generated by Django 5.1.15 on 2026-09-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_enabled', models.BooleanField(default=True, verbose_name='Afficher le badge partenaire JOJ')),
                ('sponsor_url', models.URLField(blank=True, help_text='Lien optionnel vers la page de présentation du partenariat.', verbose_name='Lien du badge partenaire')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Réglages de marque du site',
            },
        ),
    ]
